import file_22Dec21 as file

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms
By starting with 1 and 2, the first 10 terms will be:  
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
Write a python program to  

a) Add the first ten even numbers 

b) Add the first ten odd numbers 

c) Print all 3 Digit numbers and their previous 2 numbers in the sequence. For Eg: in the case 55+89=144, output should be  

         11th Fibonacci number is 144 (55 + 89) 

"""


m=file.fibonacci(30)
odd=[]
even=[]
for i in m:
    if i%2==0:
        even.append(i)
    else:
        odd.append(i)


odd_list=odd[0:10]
even_list=even[0:10]



#a) Add the first ten even numbers
even_sum = 0
for i in range(0, len(even_list)):
    even_sum = even_sum + even_list[i]
print("sum of first ten even numbers", even_sum)




#b) Add the first ten odd numbers
odd_sum = 0
for i in range(0, len(odd_list)):
    odd_sum = odd_sum + odd_list[i]
print("sum of first ten odd numbers", odd_sum)





#c) Print all 3 Digit numbers and their previous 2 numbers in the sequence. For Eg: in the case 55+89=144, output should be  11th Fibonacci number is 144 (55 + 89)
"""
for i in m:
    if (i<1000 and i>99):
        print(str(m.index(i)+1)+"th Fibonacci number is "+str(i))

"""


for i in m:
    if (i<1000 and i>99):
        a=m.index(i)+1
        b=m[a-2]
        c=m[a-3]
        #print(b,c)
        print(str(a)+"th Fibonacci number is "+str(i)+"("+str(c)+"+"+str(b)+")")


